### ISSUE TITLE
Which model is the self-model?

### ISSUE THREAD

**Issue by charliezon** [rjk2147/Task-Agnostic_Self-Modeling_Machines#1]
Dear authors,

I'm reading your paper published on science robotics. But I've no idea how you trained the self-model. What is the input and output? I thought the self-model is trained with supervised learning method. But from the source code, I can't find such kind a model. Would you please tell me in which source code the self-model is created and trained? Thank you very much.

**Comment by rjk2147** [comment]
The input data sets are found in real_widowx_train_10hz_100K_default_processed.pkl.zip and widowx_train_10hz_100K_deformed.pkl.zip. 
In order to use them you will need to unzip them and call
`test_planners.test_plan_widowx.test(env, env_learner, epochs=100, train_episodes=10, test_episodes=100, loop='open', show_model=False, load=None):`

This function 'test()' is the function that will run tests and report all results, but will also train the model if you leave the 'load' parameter as 'None'

The actual source code that is called to train the model is done in an 'env_learner' which are found in the env_learner folder.
The actual env_learner we used in the paper was the dnn_env_learner which can again be found in the env_learner folder.

**Comment by charliezon** [comment]
Thank you very much! I will try it.
